name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - os: ubuntu-latest
          - os: macOS-latest
          - os: windows-latest

    steps:
    - name: Install Linux gtk dependency
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install libgtk-3-dev
    - uses: actions/checkout@v2
    - name: Rust version
      run: rustc -V
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
